Customers.Portal/Areas/Marketing/Controllers/ManageRequestController.cs
using Customers.Abstracts;
using Customers.Abstracts.Marketing;
using Customers.Model.Marketing;
using Customers.Portal.Controllers;
using Customers.Portal.Utilities;
using Customers.Resources.GlobalRes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Customers.Portal.Areas.Marketing.Controllers
{
    [CustomAuthorize]

    public class ManageRequestController : BaseController
    {
        #region Service

        private readonly IRequestService _thisService;
        private readonly IRequestServicesService _RequestServicesService;
        private readonly CommonService _commonService;
        private readonly IRequestOfferService _RequestOfferservice;
        private readonly IRequestStatusService _RequestStatusServices;
        #endregion


        #region Constructor
        public ManageRequestController(IRequestService thisService, IRequestOfferService RequestOfferService,
            ILookupService lookupService,IRequestServicesService RequestServicesService,IRequestStatusService RequestStatusServices)
        {
            _thisService = thisService;
            _RequestOfferservice = RequestOfferService;
            _commonService = new CommonService(lookupService);
            _RequestServicesService = RequestServicesService;
            _RequestStatusServices = RequestStatusServices;
            //_CommunicationOfferSerive = CommunicationOfferSerive;
        }
        #endregion

        #region Actions

        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search(MarketingSm searchModel)
        {
            var result = _thisService.FindAll(searchModel);
            return PartialView(result);
        }

        public ActionResult Create()
        {
            MarketingVm Obj = new MarketingVm();

            ViewBag.ActivityId = _commonService.FindCustomerActivities();
            ViewBag.EmployeeId = _commonService.FindEmployees();
            ViewBag.CustId = _commonService.FindCustomers();
            ViewBag.RequestStatusId = _commonService.FindCustomerStatus();

            
            


            return PartialView("~/Areas/Marketing/Views/ManageRequest/Create.cshtml", Obj);
        }




        [HttpPost]
        public JsonResult Create(MarketingVm viewModel, int? ServiceId)
        {
            if(viewModel.Id != 0)
            {

                if (ServiceId != 0)
                {

                    RequestsServicesVm RS = new RequestsServicesVm();
                   
                    RS.RequestId = viewModel.Id;
                    RS.ServiceId = ServiceId ??0;
                    _RequestServicesService.Save(RS);
                    if (_thisService.Save(viewModel))
                    {

                        return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);


                }
                else
                {

                    if (_thisService.Save(viewModel))
                    {

                        return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);
                }
            }

           
            else
            {
                if (ServiceId != 0)
                {
                    if (_thisService.Save(viewModel))
                    {
                        RequestsServicesVm RS = new RequestsServicesVm();

                        RS.RequestId = _RequestServicesService.FindLast();
                        RS.ServiceId = ServiceId ?? 0;
                        _RequestServicesService.Save(RS);

                        return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);


                }
                else
                {

                    if (_thisService.Save(viewModel))
                    {

                        return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);
                }
            }
            
        }


        public ActionResult Edit(int id = 0)
        {
            MarketingVm obj = _thisService.GetById(id);
            ViewBag.ActivityId = _commonService.FindCustomerActivities((int)obj.ActivityId);
            ViewBag.EmployeeId = _commonService.FindEmployees((int)obj.EmployeeId);
            ViewBag.CustId = _commonService.FindCustomers((int)obj.CustId);
            ViewBag.RequestStatusId = _commonService.FindCustomerStatus((int)obj.RequestStatusId);
            if (obj == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Areas/Marketing/Views/ManageRequest/Create.cshtml", obj);
        }


        public ActionResult Details(int id)
        {
            return PartialView(_thisService.GetById(id));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            MarketingVm obj = new MarketingVm();
            obj.Id = id;
            return PartialView("~/Areas/Marketing/Views/ManageRequest/Delete.cshtml", obj);
        }
        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            if (_thisService.Delete(Id))
            {
                return Json("success," + GlobalRes.Messagedelete, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region StatusAction

        public ActionResult AddStatus(int Id)
        {
            ViewBag.RequestId = Id;
            return View();
        }
        [HttpPost]
        public JsonResult AddStatus(RequestStatusVm viewmodel)
        {
            viewmodel.CreatedBy = 0;
            viewmodel.CreatedDate = DateTime.Now;
            
            if (_RequestStatusServices.Save(viewmodel))
            {
                var Data = _thisService.GetById(viewmodel.RequestId);
                Data.RequestStatusId = viewmodel.StatusId;
                _thisService.Save(Data);
                return Json("AddStatus," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);

        }

        public ActionResult ChangeStatas(int id = 0)
        {
            RequestStatusVm obj =  new RequestStatusVm();
            obj.RequestId = id;
            return PartialView("~/Areas/Marketing/Views/ManageRequest/ChangeStatus.cshtml", obj);

            
        }
        [HttpPost]
        public JsonResult ChangeStatus(RequestStatusVm viewModel, int StatusId)
        {
            if (_RequestStatusServices.Save(viewModel))
            {
                var Data = _thisService.GetById(viewModel.RequestId);
                Data.RequestStatusId = StatusId;
                _thisService.Save(Data);
                return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);



        }
        public ActionResult GetStatus()
        {
            ViewBag.StatusId = _commonService.FindCustomerStatus();

            return PartialView("_Status");
        }

        public ActionResult GetStatusList(int? RequestId)
        {
            RequestStatusSm searchModel = new RequestStatusSm();


            var Data = _RequestStatusServices.GetServicesByRequestId(RequestId);

            return PartialView("_GetStatusList", Data);
        }
        
        [HttpGet]
        public ActionResult DeleteStatus(int id)
        {
            RequestStatusVm obj = new RequestStatusVm();
            obj.Id = id;
            return PartialView("~/Areas/Marketing/Views/ManageRequest/DeleteStatus.cshtml", obj);
        }
        [HttpPost]

        public JsonResult DeleteStatusRow(int Id)
        {
            if (_RequestStatusServices.Delete(Id))
            {
                return Json("success," + GlobalRes.Messagedelete, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }

        #endregion


        #region ServicesAction


        public ActionResult GetServices()
        {
            ViewBag.ServiceId = _commonService.FindServices();

            return PartialView("_Services");
        }


        public ActionResult AddServices(int Id)
        {
            ViewBag.RequestId = Id;
            return View();
        }
        [HttpPost]
        public JsonResult AddServices(RequestsServicesVm viewmodel)
        {
            viewmodel.CreatedBy = 0;
            viewmodel.CreatedDate = DateTime.Now;

            if (_RequestServicesService.Save(viewmodel))
            {
               
                return Json("AddServices," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetServicesList(int? RequestId)
        {
            RequestsServicesSm searchModel = new RequestsServicesSm();

Customers.Portal/Areas/Marketing/Views/ManageRequest/AddServices.cshtml
@model RequestsServicesVm
<link href="~/Scripts/select2.css" rel="stylesheet" />

@{
    var RequestId = ViewBag.RequestId;

}
@using (Html.BeginForm("AddServices", "ManageRequest", new { area = "Marketing" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <br />
                <h4 class="page-title"><a href="../../ManageRequest/Index1">رجوع للقائمه السابقه</a>--  </h4>  <h4 class="page-title"> @GlobalRes.AddOrUpdate حاله </h4>
                <br />

                <br />

            </div>
        </div>
    </div>
    @*<div class="modal-dialog modal-lg" style="width:1000px;">*@
    <div class="modal-content" style="width:1200px;">
        <div class="modal-header">
            @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
            <h4 class="modal-title">@GlobalRes.AddOrUpdate   خدمه للتسويق رقم:@RequestId </h4>
        </div>
        <div class="modal-body" style="width:1200px;">
            <div class="panel">
                @*<div class="panel-heading">
                        <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                    </div>*@
                <div class="panel-body p25 pb5">
                    <div class="tab-content pn br-n admin-form">
                        <div id="tab1_1" class="tab-pane active">
                            <input type="text" id="Id" hidden name="Id" />


                            <input type="text" value="@RequestId" id="RequestId" hidden name="RequestId" />

                          
                       
                           




                          
                            <div class="row">
                                @Html.Action("GetServices")

                                <div class="col-md-2">
                                    <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />

                                </div>
                            </div>
                            <br />
                            <br />
                            <div class="modal-header">
                                <h4 class="modal-title">الخدمات  </h4>
                            </div>
                            <br />
                            <br />


                          

                            <div class="row">
                                <div class="col-md-2">
                                </div>
                                <div class="col-md-8">
                                    @Html.Action("GetServicesList", new { RequestId = RequestId })
                                </div>

                            </div>


                            <br />



















                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    @*</div>*@

    @*<div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>*@

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>



}






@section scripts {


    <script src="@Url.Content("~/Areas/Marketing/Scripts/ManageRequest.js")"></script>

    @*<script type="text/javascript">

            $(document).ready(function () {
                ManageCustomers.init();

            })

        </script>*@
    <script src="~/Scripts/select2.min.js"></script>
    <script>
                $(document).ready(function () {
                    $('.select2').select2();
                    // $('.select5').select2();
                });
    </script>
    <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });

    </script>
}

Customers.Portal/Areas/Marketing/Views/ManageRequest/AddStatus.cshtml
@model RequestStatusVm
<link href="~/Scripts/select2.css" rel="stylesheet" />

@{
    var RequestId = ViewBag.RequestId;

}
@using (Html.BeginForm("AddStatus", "ManageRequest", new { area = "Marketing" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <br />
                <h4 class="page-title"><a href="../../ManageRequest/Index1">رجوع للقائمه السابقه</a>--  </h4>  <h4 class="page-title"> @GlobalRes.AddOrUpdate حاله </h4>
                <br />

                <br />

            </div>
        </div>
    </div>
    @*<div class="modal-dialog modal-lg" style="width:1000px;">*@
    <div class="modal-content" style="width:1200px;">
        <div class="modal-header">
            @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
            <h4 class="modal-title">@GlobalRes.AddOrUpdate   حاله للتسويق رقم:@RequestId </h4>
        </div>
        <div class="modal-body" style="width:1200px;">
            <div class="panel">
                @*<div class="panel-heading">
                        <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                    </div>*@
                <div class="panel-body p25 pb5">
                    <div class="tab-content pn br-n admin-form">
                        <div id="tab1_1" class="tab-pane active">
                            <input type="text"  id="Id" hidden name="Id" />


                            <input type="text" value="@RequestId" id="RequestId" hidden name="RequestId" />

                            @Html.Action("GetStatus")
                            <br />
                            <br />
                            <div class="row">
                                <div class="col-md-3">

                                </div>
                                
                                <div class="col-md-3">
                                    <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                </div>
                            </div>
                            <br />
                            <div class="modal-header">
                                <h4 class="modal-title">الحالات  </h4>
                            </div>
                            <br />
                            <br />




                            <br />
                            <br />
                            <br />

                            <div class="row">
                                <div class="col-md-2">
                                </div>
                                <div class="col-md-8">
                                    @Html.Action("GetStatusList", new { RequestId =RequestId })
                                </div>

                            </div>


                            <br />

                       
                            

                         
                          





                          



                           




                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    @*</div>*@

    @*<div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>*@

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>



}






@section scripts {


    <script src="@Url.Content("~/Areas/Marketing/Scripts/ManageRequest.js")"></script>

    @*<script type="text/javascript">

            $(document).ready(function () {
                ManageCustomers.init();

            })

        </script>*@
    <script src="~/Scripts/select2.min.js"></script>
    <script>
                $(document).ready(function () {
                    $('.select2').select2();
                    // $('.select5').select2();
                });
    </script>
    <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });

    </script>
}

Customers.Portal/Areas/Marketing/Views/ManageRequest/ChangeStatus.cshtml
@model RequestStatusVm


<link href="~/Scripts/select2.css" rel="stylesheet" />

@using (Html.BeginForm("ChangeStatus", "ManageRequest", new { area = "Marketing" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content" style="width: 900px;">
            <div class="modal-header">
                @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                <h4 class="modal-title">@MarketingRes.Details</h4>
            </div>
            <div class="modal-body" style="width :900px;">
                <div class="panel">
                    @*<div class="panel-heading">
                            <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                        </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                @Html.HiddenFor(model=>model.RequestId)
                                   
                                   @Html.Action("GetStatus")
                              
                                <br />

                               <br />
                                <div class="row">
                                    <div class="col-md-3">

                                    </div>
                                    <div class="col-md-3">
                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                                    </div>
                                </div>
                                <br />
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">الحالات  </h4>
                                </div>
                                <br />
                                <br />

                               


                                <br />
                                <br />
                                <br />

                                <div class="row">
                                    <div class="col-md-2">
                                    </div>
                                    <div class="col-md-8">
                                        @Html.Action("GetStatusList", new { RequestId = Model.RequestId })
                                    </div>

                                </div>


                                <br />
                               
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

                    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>
}



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

<script src="~/Scripts/select2.min.js"></script>
<script>
        $(document).ready(function () {
            $('.select2').select2();
            // $('.select5').select2();
        });
</script>

Customers.Portal/Areas/Marketing/Views/ManageRequest/Create.cshtml
@model MarketingVm


<link href="~/Scripts/select2.css" rel="stylesheet" />

@using (Html.BeginForm("Create", "ManageRequest", new { area = "Marketing" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content" style="width: 900px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@MarketingRes.Details</h4>
            </div>
            <div class="modal-body" style="width :900px;">
                <div class="panel">
                    @*<div class="panel-heading">
                        <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                    </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="row">
                                    <div class="col-md-2">
                                        @Html.HiddenFor(model => model.Id)
                                        @Html.LabelFor(mode => mode.CustId, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">

                                        @Html.EditorFor(model => model.CustId, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>
                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.ActivityId, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.EditorFor(model => model.ActivityId, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>
                                </div>
                                <br />

                                <div class="row">
                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.EmployeeId, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>
                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.RequestStatusId, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        @Html.EditorFor(model => model.RequestStatusId, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.Note, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <textarea name="Note" id="Note" class="form-control" ></textarea>
                                    </div>
                                    
                                </div>
                                <br />
                                <br />

                                <div class="row">
                                    <div class="col-md-6">

                                    </div>
                                    <div class="col-md-3">
                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                                    </div>
                                </div>
                               <br />
                                <br />
                                @*<div class="modal-header">
                                    <h4 class="modal-title">الخدمات  </h4>
                                </div>
                                <br />
                                <br />
                                <div class="row">
                                    @Html.Action("GetServices")

                               <div class="col-md-2">
                                   <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />

                               </div>
                                </div>


                                <br />
                                <br />
                                <br />

                                <div class="row">
                                    <div class="col-md-2">
                                    </div>
                                    <div class="col-md-8">
                                        @Html.Action("GetServicesList", new { RequestId=Model.Id})
                                    </div>
                                   
                                </div>


                                <br />*@
                               
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
                    </div>

                    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>
                    }



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

<script src="~/Scripts/select2.min.js"></script>
<script>
        $(document).ready(function () {
            $('.select2').select2();
            // $('.select5').select2();
        });
</script>

Customers.Portal/Areas/Marketing/Views/ManageRequest/Delete.cshtml
@model MarketingVm


    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Customers.Portal/Areas/Marketing/Views/ManageRequest/DeleteServices.cshtml
@model RequestsServicesVm


<div class="modal-dialog" style="width: 900px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
        </div>
        <div class="modal-body" style="width :900px;">

            <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
            <div class="row">
                <div class="col-md-3">
                    <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteServicesRow(@Model.Id)" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

Customers.Portal/Areas/Marketing/Views/ManageRequest/_Services.cshtml
@model RequestsServicesVm




    <div class="col-md-2">
        @Html.LabelFor(mode => mode.ServiceId, htmlAttributes: new { @class = "control-label" })
    </div>
    <div class="col-md-4">

        @Html.EditorFor(model => model.ServiceId, new { htmlAttributes = new { @class = "form-control input-circle" } })
    </div>