Customers.Portal/Areas/SupportRequest/Controllers/ManageSupportRequestController.cs
using Customers.Abstracts;
using Customers.Abstracts.SupportRequests;
using Customers.Model.SupportRequests;
using Customers.Portal.Controllers;
using Customers.Portal.Utilities;
using Customers.Resources.GlobalRes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Customers.Portal.Areas.SupportRequest.Controllers
{
    [CustomAuthorize]

    public class ManageSupportRequestController : BaseController
    {
        #region Services

        private readonly ISupportRequestService _thisService;
        private readonly CommonService _commonService;


        #endregion

        #region Constructor
        public ManageSupportRequestController(ISupportRequestService thisService, ILookupService lookupService)
        {
            _thisService = thisService;
            _commonService = new CommonService(lookupService);

        }
        #endregion


        #region Actions

        public ActionResult Index1()
        {
            if (Customers.Helpers.Utilities.ResourcesReader.ISAdmin == true)
            {
                ViewBag.userlogin = 1;

            }
            else if (Customers.Helpers.Utilities.ResourcesReader.UserTypeId == 2)
            {
                ViewBag.userlogin = 2;
            }
            else if (Customers.Helpers.Utilities.ResourcesReader.UserTypeId == 1)
            {
                ViewBag.userlogin = 1;
            }
            else
                ViewBag.userlogin = 1;
            return View();
        }
        public ActionResult Search(int? customerId,SupportRequestsSm viewmodel)
        {

            if (Customers.Helpers.Utilities.ResourcesReader.ISAdmin == true)
            {
                ViewBag.userlogin = 1;
                var result = _thisService.FindAll(viewmodel);
                return PartialView(result);
            }
            else if (Customers.Helpers.Utilities.ResourcesReader.UserTypeId == 2)
            {
                ViewBag.userlogin = 2;
                customerId = Customers.Helpers.Utilities.ResourcesReader.UserId;
                var result = _thisService.GetByCustomerId((int)customerId);
                return PartialView(result);
            }

            else if (Customers.Helpers.Utilities.ResourcesReader.UserTypeId == 1)
            {
                ViewBag.userlogin = 1;
                var result = _thisService.GetByEmployeeId((int)customerId);
                return PartialView(result);
            }
            else
                ViewBag.userlogin = 1;
                return PartialView();

        }

        public ActionResult Create()
        {
            SupportRequestsVm Obj = new SupportRequestsVm();
            ViewBag.DepartmentId = _commonService.FindDepartments();
            return PartialView("~/Areas/SupportRequest/Views/ManageSupportRequest/Create.cshtml", Obj);
        }
        [HttpPost]
        public JsonResult Create(SupportRequestsVm viewModel)
        {

            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileNameWithExtension = Path.GetFileName(file.FileName);
                    var fileNameOnly = Path.GetFileNameWithoutExtension(file.FileName);
                    string RootPath = Server.MapPath("~/Uploaded/SupportRequests/");
                    if (!Directory.Exists(RootPath))
                    {
                        Directory.CreateDirectory(RootPath);
                    }
                    var unique = new Guid();
                    var path = Path.Combine(RootPath, fileNameOnly + unique + Path.GetExtension(file.FileName));
                    file.SaveAs(path);
                    viewModel.Image = fileNameOnly + unique + Path.GetExtension(file.FileName);

                }
            }

            viewModel.CustomerId = Customers.Helpers.Utilities.ResourcesReader.UserId;
            if (_thisService.Save(viewModel))
            {
                return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);

        }
        public ActionResult Edit(int id = 0)
        {
            SupportRequestsVm obj = _thisService.GetById(id);
            ViewBag.DepartmentId = _commonService.FindDepartments(obj.DepartmentId);

            if (obj == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Areas/SupportRequest/Views/ManageSupportRequest/Create.cshtml", obj);
        }

        public ActionResult AddDetails(int Id)
        {
            SupportRequestsVm obj = _thisService.GetById(Id);
            return PartialView("~/Areas/SupportRequest/Views/ManageSupportRequest/AddDetails.cshtml", obj);

        }
        [HttpPost]
        public JsonResult AddDetails(SupportRequestsVm viewModel)
        {

            
            if (_thisService.Save(viewModel))
            {
                return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);

        }
        public ActionResult ChangeToEmployee(int Id)
        {

            SupportRequestsVm obj = _thisService.GetById(Id);
            ViewBag.EmployeeId = _commonService.FindEmployees((int)obj.EmployeeId);


            return PartialView("~/Areas/SupportRequest/Views/ManageSupportRequest/ChangeToEmployee.cshtml", obj);
        }
        [HttpPost]
        public JsonResult ChangeToEmployee(SupportRequestsVm viewModel)
        {

            //viewModel.EmployeeId = Customers.Helpers.Utilities.ResourcesReader.UserId;
            if (_thisService.Save(viewModel))
            {
                return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);

        }


        public ActionResult Details(int id)
        {
            return PartialView(_thisService.GetById(id));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            SupportRequestsVm obj = new SupportRequestsVm();
            obj.Id = id;
            return PartialView("~/Areas/SupportRequest/Views/ManageSupportRequest/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            if (_thisService.Delete(Id))
            {
                return Json("success," + GlobalRes.Messagedelete, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Customers.Portal/Areas/SupportRequest/Views/ManageSupportRequest/AddDetails.cshtml
@model SupportRequestsVm



@using (Html.BeginForm("AddDetails", "ManageSupportRequest", new { area = "SupportRequest" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Image)

    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content" style="width: 900px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@BasicInputRes.Details</h4>
            </div>
            <div class="modal-body" style="width :900px;">
                <div class="panel">
                    @*<div class="panel-heading">
                            <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                        </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="row">
                                    @Html.HiddenFor(model => model.Id)
                                    @Html.HiddenFor(model => model.EmployeeId)
                                    @Html.HiddenFor(model => model.CustomerId)
                                    @Html.HiddenFor(model => model.DescriptionProblem)
                                    @Html.HiddenFor(model => model.DepartmentId)
                                    @Html.HiddenFor(model => model.Date)
                                    @Html.HiddenFor(model => model.HourDate)
                                    @Html.HiddenFor(model => model.Image)
                                    @Html.HiddenFor(model => model.CreatedBy)




                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.Details, htmlAttributes: new { @class = "control-label" })
                                    </div>

                                    <div class="col-md-4">
                                        <textarea id="Details" name="Details" value="@Model.Details" class="form-control"> </textarea>

                                      
                                    </div>

                                </div>
                             
                                <br />
                               

                                <br />
                                <div class="row">
                                    <div class="col-md-6">

                                    </div>
                                    <div class="col-md-3">
                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

                    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>
}



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

Customers.Portal/Areas/SupportRequest/Views/ManageSupportRequest/ChangeToEmployee.cshtml
@model SupportRequestsVm



@using (Html.BeginForm("ChangeToEmployee", "ManageSupportRequest", new { area = "SupportRequest" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Image)

    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content" style="width: 900px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@BasicInputRes.Details</h4>
            </div>
            <div class="modal-body" style="width :900px;">
                <div class="panel">
                    @*<div class="panel-heading">
                            <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                        </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="row">
                                    @Html.HiddenFor(model => model.Id)
                                    @Html.HiddenFor(model => model.Id)
                                    @Html.HiddenFor(model => model.CustomerId)
                                    @Html.HiddenFor(model => model.DescriptionProblem)
                                    @Html.HiddenFor(model => model.DepartmentId)
                                    @Html.HiddenFor(model => model.Date)
                                    @Html.HiddenFor(model => model.HourDate)
                                    @Html.HiddenFor(model => model.Image)
                                    @Html.HiddenFor(model => model.CreatedBy)
                                    @Html.HiddenFor(model => model.Details)








                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.EmployeeId, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">

                                        @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>

                                </div>

                                <br />


                                <br />
                                <div class="row">
                                    <div class="col-md-6">

                                    </div>
                                    <div class="col-md-3">
                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>
}



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

Customers.Portal/Areas/SupportRequest/Views/ManageSupportRequest/Create.cshtml
@model SupportRequestsVm



@using (Html.BeginForm("Create", "ManageSupportRequest", new { area = "SupportRequest" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Image)

    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content" style="width: 900px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@BasicInputRes.Details</h4>
            </div>
            <div class="modal-body" style="width :900px;">
                <div class="panel">
                    @*<div class="panel-heading">
                        <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                    </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="row">
                                    @Html.HiddenFor(model => model.Id)
                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.DepartmentId, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">

                                        @Html.EditorFor(model => model.DepartmentId, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>

                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.DescriptionProblem, htmlAttributes: new { @class = "control-label" })
                                    </div>

                                    <div class="col-md-4">
                                        <textarea  id="DescriptionProblem" name="DescriptionProblem" value="@Model.DescriptionProblem" class="form-control" > </textarea>

                                        @*@Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                  
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-2">
                                        @*<input type="text" id="NameEn" name="NameEn" value="@Model.NameEn" class="form-control" />*@

                                        @Html.LabelFor(mode => mode.Date, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <input type="date" id="Date" name="Date" class="form-control" />

                                        @*@Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                    <div class="col-md-2">
                                        @Html.HiddenFor(model => model.Id)
                                        @Html.LabelFor(mode => mode.HourDate, htmlAttributes: new { @class = "control-label" })
                                    </div>

                                    <div class="col-md-4">
                                        <input type="text" id="HourDate" name="HourDate" class="form-control" />

                                        @*@Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control input-circle" } })*@

                                    </div>
                                </div>
                                    <br />
                                    <div class="row">
                                        <div class="col-md-2">
                                            @*<input type="text" id="NameEn" name="NameEn" value="@Model.NameEn" class="form-control" />*@

                                            @Html.LabelFor(mode => mode.Image, htmlAttributes: new { @class = "control-label" })
                                        </div>
                                        <div class="col-md-4">
                                            <input type="file" id="file" name="file" value="@Model.Image" class="form-control" />

                                            @*@Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                        </div>
                                    </div>
                                   
                                  
                                <br />
                                <div class="row">
                                    <div class="col-md-6">

                                    </div>
                                    <div class="col-md-3">
                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
                    </div>

                    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>
                    }



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

Customers.Portal/Areas/SupportRequest/Views/ManageSupportRequest/Delete.cshtml
@model SupportRequestsVm


    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Customers.Portal/Areas/SupportRequest/Views/ManageSupportRequest/GetContact.cshtml
@model IEnumerable<Customers.Model.BasicInput.CommunicationOfficerVm>


<link href="~/Scripts/select2.css" rel="stylesheet" />

@using (Html.BeginForm("", "", new { area = "Marketing" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content" style="width: 900px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@MarketingRes.Details</h4>
            </div>
            <div class="modal-body" style="width :900px;">
                <div class="panel">
                    @*<div class="panel-heading">
                            <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                        </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="card-box table-responsive">
                                            <table class="table table-hover table-bordered datatable" width="100%">
                                                <thead>
                                                    <tr>

                                                        <th>الاسم</th>
                                                        <th>الوظيفه</th>
                                                        <th>الهاتف</th>
                                                        <th>الاميل</th>




                                                        @*<th>Actions</th>*@
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var item in Model)
                                                    {
                                                        <tr>

                                                            <td>@item.Name</td>
                                                            <td>@item.JobeName</td>
                                                            <td>@item.PhoneNumber</td>
                                                            <td>@item.Email</td>





                                                            @*<td>
                            <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                                <button class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-cog fa-lg"></i>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-xs pull-right">
                                    <li>
                                        <button type="button" class="fa fa-pencil-square-o" id="btnUpdate" onclick="EditComm(@item.Id,'@item.Name','@item.JobeName','@item.PhoneNumber','@item.Email')"></button>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <button type="button" class="fa fa-trash" id="btnDelete" onclick="DeleteComm(@item.Id)"></button>
                                    </li>
                                    <li class="divider"></li>
                                    <li class="text-align-center">
                                        <a href="javascript:void(0);"><i class="fa fa-times" aria-hidden="true"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </td>*@

                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>


                                    </div>
                                </div>

                             

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>
}



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

<script src="~/Scripts/select2.min.js"></script>
<script>
        $(document).ready(function () {
            $('.select2').select2();
            // $('.select5').select2();
        });
</script>


<script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


</script>

Customers.Portal/Areas/SupportRequest/Views/ManageSupportRequest/Index1.cshtml
@{
    ViewBag.Title = GlobalRes.SupportRequests;
}

<div id="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <br />
                <h4 class="page-title"><a href="~/Home/index">@GlobalRes.MainPage</a>--  </h4>  <h4 class="page-title"> @GlobalRes.SupportRequests </h4>
                <br />

            </div>
        </div>
    </div>
    <!-- widget grid -->
    <section id="widget-grid" class="">

        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    @if (ViewBag.userlogin == 2)
                    {
                    <input type="button" id="AddNew" onclick="Create()" class="btn yellow " value="@GlobalRes.btnAdd" />
                    }
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {

<script src="@Url.Content("~/Areas/SupportRequest/Scripts/ManageSupportRequest.js")"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            ManageSupportRequest.init();
      
        })

    </script>

}