Customers.Portal/Areas/BasicInput/Controllers/ManagePricesOffersController.cs
using Customers.Abstracts;
using Customers.Abstracts.BasicInput;
using Customers.Model.BasicInput;

using Customers.Portal.Controllers;
using Customers.Portal.Utilities;
using Customers.Resources.GlobalRes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Customers.Portal.Areas.BasicInput.Controllers
{
    //[CustomAuthorize]

    public class ManagePricesOffersController : BaseController
    {
        #region Service

        private readonly IPriceOffersService _thisService;
        private readonly IPriceOffersConditionsService _PriceOffersConditionsService;
        private readonly CommonService _commonService;
        #endregion


        #region Constructor
        public ManagePricesOffersController(IPriceOffersService thisService, ILookupService lookupService, IPriceOffersConditionsService PriceOffersConditionsService)
        {
            _thisService = thisService;
            _commonService = new CommonService(lookupService);
            _PriceOffersConditionsService = PriceOffersConditionsService;
        }
        #endregion

        #region Actions

        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search(BasicInputSm searchModel)
        {
            var result = _thisService.FindAll(searchModel);
            return PartialView(result);
        }

        public ActionResult Create()
        {
            BasicInputVm Obj = new BasicInputVm();

            return PartialView("~/Areas/BasicInput/Views/ManagePricesOffers/Create.cshtml", Obj);
        }


        public ActionResult GetConditions()
        {
            ViewBag.ConditionsId = _commonService.FindConditions();

            return PartialView("_Conditions");
        }


        [HttpPost]
        public JsonResult Create(BasicInputVm viewModel)
        {

            if (viewModel.NameEn == null || viewModel.NameEn == "")
                viewModel.NameEn = viewModel.NameAr;


          
                if (_thisService.Save(viewModel))
                {
                    
                    return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);

                }
                else
                    return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);
            
        }



        public ActionResult Edit(int id = 0)
        {
            BasicInputVm obj = _thisService.GetById(id);

            if (obj == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Areas/BasicInput/Views/ManagePricesOffers/Create.cshtml", obj);
        }


        public ActionResult Details(int id)
        {
            return PartialView(_thisService.GetById(id));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            BasicInputVm obj = new BasicInputVm();
            obj.Id = id;
            return PartialView("~/Areas/BasicInput/Views/ManagePricesOffers/Delete.cshtml", obj);
        }
        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            if (_thisService.Delete(Id))
            {
                return Json("success," + GlobalRes.Messagedelete, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }

        #endregion


        #region Condition
        public ActionResult AddCondition(int Id)
        {
            ViewBag.PriceOfferId = Id;
            ViewBag.PricOfferName = _thisService.GetById(Id).NameAr;
            return View();
        }

        [HttpPost]
        public JsonResult AddCondition(int ConditionsId, int PriceOfferId)
        {
            PriceOffersConditionVm C = new PriceOffersConditionVm();
            C.ConditionsId = ConditionsId /*_thisService.FindLast(viewModel).LastOrDefault().Id*/;
            C.PriceOffersId = PriceOfferId;
            if (_PriceOffersConditionsService.Save(C))
                return Json("SuEditItems," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);


            //return PartialView("~/Areas/BasicInput/Views/ManageContracts/AddItems.cshtml", obj);
        }
        public ActionResult GetCondionsList(int? Id)
        {
            //ContractsItemsSm searchModel = new ContractsItemsSm();


            var Data = _PriceOffersConditionsService.GetByPriceOffersId(Id);

            return PartialView("_GetConditionsList", Data);
        }


        public ActionResult DeleteItems(int id)
        {
            ContractsItemsVm obj = new ContractsItemsVm();
            obj.Id = id;
            return PartialView("~/Areas/BasicInput/Views/ManagePricesOffers/DeleteItems.cshtml", obj);
        }


        public JsonResult DeleteItemsRow(int Id)
        {

            if (_PriceOffersConditionsService.Delete(Id))
            {



                return Json("success," + GlobalRes.Messagedelete, JsonRequestBehavior.AllowGet);

            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Customers.Portal/Areas/BasicInput/Views/ManagePricesOffers/AddCondition.cshtml
@model ContractsItemsVm
<link href="~/Scripts/select2.css" rel="stylesheet" />

@{
    var PriceOfferId = ViewBag.PriceOfferId;
    var PriceOfferName = ViewBag.PriceOfferName;
}
@using (Html.BeginForm("AddCondition", "ManagePricesOffers", new { area = "BasicInput" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <br />
                <h4 class="page-title"><a href="../../ManagePricesOffers/Index1">رجوع للقائمه السابقه</a>--  </h4>  <h4 class="page-title"> @GlobalRes.AddOrUpdate شرط </h4>
                <br />

                <br />

            </div>
        </div>
    </div>
    @*<div class="modal-dialog modal-lg" style="width:1000px;">*@
    <div class="modal-content" style="width:1200px;">
        <div class="modal-header">
            @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
            <h4 class="modal-title">@GlobalRes.AddOrUpdate  شرط لعرض السعر   : @PriceOfferName </h4>
        </div>
        <div class="modal-body" style="width:1200px;">
            <div class="panel">
                @*<div class="panel-heading">
                        <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                    </div>*@
                <div class="panel-body p25 pb5">
                    <div class="tab-content pn br-n admin-form">
                        <div id="tab1_1" class="tab-pane active">


                            <input type="text" value="@PriceOfferId" id="PriceOfferId" hidden name="PriceOfferId" />


                 
        <br />
        <div class="row">
            @Html.Action("GetConditions")


            <div class="col-md-4">


                <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />

            </div>
        </div>


                           
        <br />
                            <div class="modal-header">
                                <h4 class="modal-title">الشروط </h4>
                            </div>

        <br />
        <div class="row">
            <div class="col-md-2">

            </div>
            <div class="col-md-8">
                @Html.Action("GetCondionsList", new { Id = PriceOfferId })


            </div>
        </div>


        






                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
        @*</div>*@

        @*<div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>*@

        <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>



}



<script>
            //$(document).ready(function () {
            //    $("input[type=text]").addClass("gui-input");
            //});

            function EditComm(Id, Name, JobName, PhoneNumber, Email) {
                $("#CommName").val(Name);
                $("#JobName").val(JobName);
                $("#PhoneNumber").val(PhoneNumber);
                $("#Email").val(Email);
                $("#CommId").val(Id);



            }

</script>



@section scripts {


    <script src="@Url.Content("~/Areas/BasicInput/Scripts/ManagePricesOffers.js")"></script>

    @*<script type="text/javascript">

            $(document).ready(function () {
                ManageCustomers.init();

            })

        </script>*@
    <script src="~/Scripts/select2.min.js"></script>
    <script>
                $(document).ready(function () {
                    $('.select2').select2();
                    // $('.select5').select2();
                });
    </script>
    <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });

    </script>
}

Customers.Portal/Areas/BasicInput/Views/ManagePricesOffers/Create.cshtml
@model BasicInputVm


<link href="~/Scripts/select2.css" rel="stylesheet" />

@using (Html.BeginForm("Create", "ManagePricesOffers", new { area = "BasicInput" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog modal-lg" style="width:1000px;">
        <div class="modal-content" style="width:1000px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@GlobalRes.AddOrUpdate &nbsp; &nabla; @GlobalRes.PriceOffers</h4>
            </div>
            <div class="modal-body" style="width:1000px;">
                <div class="panel">
                    @*<div class="panel-heading">
                            <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                        </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="form-group row">
                                    <div class="col-md-2">
                                        @Html.HiddenFor(model => model.Id)
                                        @Html.LabelFor(mode => mode.NameAr, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">


                                        <input type="text" class="form-control" id="NameAr" name="NameAr" value="@Model.NameAr">
                                    </div>

                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.NameEn, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="NameEn" name="NameEn" value="@Model.NameEn">

                                        @*@Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                </div>

                                <br />
                                <br />
                                <div class="row">
                                    <div class="col-md-5">

                                    </div>
                                    <div class="col-md-5">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>

                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                    </div>
                                </div>


                                <br />
                               
                               
                               
                                @*<div class="modal-header">
                                    <h4 class="modal-title">الشروط </h4>
                                </div>

                                <br />
                                <div class="row">
                                    @Html.Action("GetConditions")


                                    <div class="col-md-4">


                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />

                                    </div>
                                </div>*@
                           
                               
                                @*<br />
                                <br />
                                <br />
                                <div class="row">
                                    <div class="col-md-2">

                                    </div>
                                    <div class="col-md-8">
                                        @Html.Action("GetCondionsList", new { Id = Model.Id })


                                    </div>
                                </div>*@
                                

                                @*@if (Model.Id != 0)
                                {
                                    <div class="row">
                                        <div class="col-md-2"></div>
                                        <div class="col-md-10">
                                            <br />
                                            @Html.Action("CommunicationOfficer", new { Id = Model.Id })


                                        </div>
                                    </div>
                                }
                                <br />*@
                               
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

                    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>
                    }



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>


<script src="~/Scripts/select2.min.js"></script>
<script>
        $(document).ready(function () {
            $('.select2').select2();
            // $('.select5').select2();
        });
</script>

Customers.Portal/Areas/BasicInput/Views/ManagePricesOffers/Delete.cshtml
@model BasicInputVm


    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Customers.Portal/Areas/BasicInput/Views/ManagePricesOffers/DeleteItems.cshtml
@model ContractsItemsVm


<div class="modal-dialog" style="width: 900px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
        </div>
        <div class="modal-body" style="width :900px;">

            <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
            <div class="row">
                <div class="col-md-3">
                    <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteItemsRow(@Model.Id)" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

Customers.Portal/Areas/BasicInput/Views/ManagePricesOffers/Index1.cshtml
@{
    ViewBag.Title = GlobalRes.PriceOffers;
}

<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/Home/index">@GlobalRes.MainPage</a>--  </h4>  <h4 class="page-title"> @GlobalRes.PriceOffers </h4>
                    <br />

                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <input type="button" id="AddNew" onclick="Create()" class="btn yellow " value="@GlobalRes.btnAdd" />
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {

<script src="@Url.Content("~/Areas/BasicInput/Scripts/ManagePricesOffers.js")"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            ManageOfferPrices.init();
      
        })

    </script>
}

Customers.Portal/Areas/BasicInput/Views/ManagePricesOffers/Search.cshtml
@model IEnumerable<BasicInputVm>

<div class="">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" width="100%">
                <thead>
                    <tr>
                        <th>@BasicInputRes.Id</th>
                        <th>@BasicInputRes.NameAr</th>
                        <th>@BasicInputRes.NameEn</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.NameAr</td>
                            <td>@item.NameEn</td>

                            <td>
                                <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                                    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-cog fa-lg"></i>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-xs pull-right">
                                        <li class="text-align-center">
                                            <button type="button" class="btn btn-success   waves-effect waves-light m-b-0" id="btnUpdate" onclick="Edit(@item.Id)">@GlobalRes.btnEdit</button>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="text-align-center">
                                            <a type="button" class="btn btn-warning  waves-effect waves-light m-b-0"  href="@Url.Action("AddCondition", new { Id=item.Id})"> اضافه شرط</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="text-align-center">
                                            <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete(@item.Id)"> @GlobalRes.btnDelete</button>
                                        </li>
                                        @*<li class="divider"></li>
                                        <li class="text-align-center">
                                            <a href="javascript:void(0);" class="btn btn-warning waves-effect waves-light m-b-0" aria-hidden="true">@GlobalRes.btnCancel</a>
                                        </li>*@
                                    </ul>
                                </div>
                            </td>


                        </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
</div>

        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>

Customers.Portal/Areas/BasicInput/Views/ManagePricesOffers/_Conditions.cshtml
@model PriceOffersConditionVm



    <div class="col-md-2">
        @Html.LabelFor(mode => mode.ConditionsId, htmlAttributes: new { @class = "control-label" })
    </div>
    <div class="col-md-4">

        @Html.EditorFor(model => model.ConditionsId, new { htmlAttributes = new { @class = "form-control input-circle" } })
    </div>

Customers.Portal/Areas/BasicInput/Views/ManagePricesOffers/_GetConditionsList.cshtml
@model IEnumerable<PriceOffersConditionVm>

<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" width="100%">
                <thead>
                    <tr>

                        <th>الكود</th>
                        <th>اسم الشرط</th>





                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>

                            <td>@item.Id</td>
                            <td>@item.ConditionsName</td>






                            <td>
                                <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                                    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-cog fa-lg"></i>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-xs pull-right">
                                        <li>
                                            @*<button type="button" class="fa fa-pencil-square-o" id="btnUpdate" onclick="EditComm(@item.Id,'@item.Name','@item.JobeName','@item.PhoneNumber','@item.Email')"></button>*@
                                        </li>
                                        <li class="divider"></li>

                                        <li class="text-align-center">
                                            <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="DeleteItems(@item.Id)"> @GlobalRes.btnDelete</button>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="text-align-center">
                                            <a href="javascript:void(0);" class="btn btn-warning waves-effect waves-light m-b-0" aria-hidden="true">@GlobalRes.btnCancel</a>
                                        </li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>

        </div>
    </div>