Customers.Portal/Areas/BasicInput/Controllers/ManageCustomersController.cs
using Customers.Abstracts;
using Customers.Abstracts.Administration;
using Customers.Abstracts.BasicInput;
using Customers.Model.Administration;
using Customers.Model.BasicInput;
using Customers.Portal.Controllers;
using Customers.Portal.Utilities;
using Customers.Resources.GlobalRes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Customers.Portal.Areas.BasicInput.Controllers
{
    //[CustomAuthorize]

    public class ManageCustomersController : BaseController
    {
        #region Service

        private readonly ICustomerService _thisService;
        private readonly ICommunicationOfficerService _CommunicationOfferSerive;
        private readonly CommonService _commonService;
        private readonly IAdministrationServiec _AdminService;
        #endregion


        #region Constructor
        public ManageCustomersController(ICustomerService thisService,IAdministrationServiec AdminService,
            ILookupService lookupService,ICommunicationOfficerService CommunicationOfferSerive)
        {
            _thisService = thisService;
            _AdminService = AdminService;
            _commonService = new CommonService(lookupService);
            _CommunicationOfferSerive = CommunicationOfferSerive;
        }
        #endregion

        #region Actions

        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search(CustomerSm searchModel)
        {
            var result = _thisService.FindAll(searchModel);
            return PartialView(result);
        }

        public ActionResult Create()
        {
            CustomerVm Obj = new CustomerVm();
            ViewBag.CustomerActivityId = _commonService.FindCustomerActivities();
            //return PartialView("~/Areas/BasicInput/Views/ManageCustomers/Create.cshtml", Obj);
            return View(Obj);
        }

      

      
        [HttpPost]
        public JsonResult Create(CustomerVm viewModel,string PhoneNumber, string JobName,string Email,string CommName ,int? CommId)
        {
            if (viewModel.NameEn == null || viewModel.NameEn == "")
                viewModel.NameEn = viewModel.NameAr;

            if (viewModel.Id == 0)
            {
                _thisService.Save(viewModel);
                AuthUserVm User = new AuthUserVm();
                User.UserName = viewModel.UserName;
                User.Password = viewModel.Password;
                User.Name = viewModel.NameAr;
                User.IsActive = true;
                User.TypeId = 2;
                User.UserId = _thisService.FindLast();
            
                _AdminService.Save(User);
                CommunicationOfficerVm Cmof = new CommunicationOfficerVm();
                Cmof.Name = CommName;
                Cmof.JobeName = JobName;
                Cmof.Email = Email;
                Cmof.PhoneNumber = PhoneNumber;
                Cmof.CustomerId = _thisService.FindLast();
                var Id = 0;

                if ( _CommunicationOfferSerive.Save(Cmof))
                {
                
                    return Json("success," +Id , JsonRequestBehavior.AllowGet);
                }
                else
                    return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);
            }
            else
            {

                if (CommName != "")
                {
                    CommunicationOfficerVm Cmof = new CommunicationOfficerVm();
                    Cmof.Name = CommName;
                    Cmof.JobeName = JobName;
                    Cmof.Email = Email;
                    if (CommId != null)
                    Cmof.Id =(int) CommId;
                    Cmof.PhoneNumber = PhoneNumber;
                    Cmof.CustomerId = viewModel.Id;
                    if (_CommunicationOfferSerive.Save(Cmof))
                    {
                        var Id = viewModel.Id;
                        
                        return Json("success," + Id, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);

                    }
                }
                else
                     if (_thisService.Save(viewModel))
                {
                    _thisService.Save(viewModel);
                    AuthUserVm User = new AuthUserVm();
                    User.UserName = viewModel.UserName;
                    User.Password = viewModel.Password;
                    User.Name = viewModel.NameAr;
                    User.IsActive = true;
                    User.TypeId = 2;
                    User.UserId = User.UserId = _thisService.FindLast();
                    

                    _AdminService.Save(User);
                    return Json("success," + GlobalRes.MessageSuccuss.ToString(), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("error," + GlobalRes.MessageError.ToString(), JsonRequestBehavior.AllowGet);

                }
            }
        }


        public ActionResult Edit(int id = 0)
        {
            CustomerVm obj = _thisService.GetById(id);
            ViewBag.CustomerActivityId = _commonService.FindCustomerActivities(obj.CustomerActivityId);

            if (obj == null)
            {
                return HttpNotFound();
            }
            //return PartialView("~/Areas/BasicInput/Views/ManageCustomers/Create.cshtml", obj);
            return View("Create",obj);

        }


        public ActionResult Details(int id)
        {
            return PartialView(_thisService.GetById(id));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            CustomerVm obj = new CustomerVm();
            obj.Id = id;
            return PartialView("~/Areas/BasicInput/Views/ManageCustomers/Delete.cshtml", obj);
        }
        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            if (_thisService.Delete(Id))
            {
                return Json("success," + GlobalRes.Messagedelete, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }

        #endregion

        /// <summary>
        /// / CommunicationOfficer
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        #region CommunicationOfficer Action

      
        [HttpGet]
        public ActionResult CommunicationOfficer(int? Id)
        {
            CommunicationOfficerSm searchModel = new CommunicationOfficerSm();


            var Data = _CommunicationOfferSerive.GetByCustomerId(Id);

            return PartialView("_CommunicationOfficer", Data);
        }

        public ActionResult DeleteComm(int id)
        {
            CommunicationOfficerVm obj = new CommunicationOfficerVm();
            obj.Id = id;
        
            return PartialView("~/Areas/BasicInput/Views/ManageCustomers/DeleteComm.cshtml", obj);
        }


        public JsonResult DeleteCommRow(int Id)
        {
            
            if (_CommunicationOfferSerive.Delete(Id))
            {
             
               

                return Json("success," + GlobalRes.Messagedelete,  JsonRequestBehavior.AllowGet);

            }
            else
                return Json("error," + GlobalRes.MessageError, JsonRequestBehavior.AllowGet);
        }
        #endregion

    }
}

Customers.Portal/Areas/BasicInput/Views/ManageCustomers/Create.cshtml
@model CustomerVm

@{
    var Id = ViewBag.Id;
}
<link href="~/Scripts/select2.css" rel="stylesheet" />


@using (Html.BeginForm("Create", "ManageCustomers", new { area = "BasicInput" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <br />
                <h4 class="page-title"><a href="~/Home/index">@GlobalRes.MainPage</a>--  </h4>  <h4 class="page-title"> @GlobalRes.AddOrUpdateCustomer </h4>
                <br />

            </div>
        </div>
        </div>
        @*<div class="modal-dialog modal-lg" style="width:1000px;">*@
        <div class="modal-content" style="width:1200px;">
            <div class="modal-header">
                @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                <h4 class="modal-title">@GlobalRes.CustomerDetails</h4>
            </div>
            <div class="modal-body" style="width:1200px;">
                <div class="panel">
                    @*<div class="panel-heading">
                            <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                        </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="form-group row">
                                    <div class="col-md-2">

                                        @Html.HiddenFor(model => model.Id)
                                        @Html.LabelFor(mode => mode.NameAr, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        @*@Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control" } })*@


                                        <input type="text" class="form-control" id="NameAr" name="NameAr" value="@Model.NameAr">
                                    </div>

                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.NameEn, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="NameEn" name="NameEn" value="@Model.NameEn">

                                        @*@Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                </div>


                                <br />
                                <div class="row">

                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.CustomerActivityId, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">

                                        @Html.EditorFor(model => model.CustomerActivityId, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>

                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.CustomerAddress, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="CustomerAddress" name="CustomerAddress" value="@Model.CustomerAddress">

                                        @*@Html.EditorFor(model => model.CustomerAddress, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>

                                </div>

                                <br />
                                <div class="row">
                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.CustomerWebSite, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="CustomerWebSite" name="CustomerWebSite" value="@Model.CustomerWebSite">

                                        @*@Html.EditorFor(model => model.CustomerWebSite, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>

                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.Details, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <textarea class="form-control" id="Details" name="Details" placeholder="@Model.Details"></textarea>

                                        @*@Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                </div>
                                <br />
                                @if (Model.Id == 0)
                                {
                                <div class="row">
                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.UserName, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="UserName" name="UserName" value="@Model.UserName">

                                        @*@Html.EditorFor(model => model.CustomerWebSite, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>

                                    <div class="col-md-2">
                                        @Html.LabelFor(mode => mode.Password, htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-4">
                                        <input type="password" class="form-control" id="Password" name="Password" value="@Model.Password">

                                        @*@Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                </div>
                                }


                                <br />
                                <br />
                                <div class="row">
                                    <div class="col-md-6">

                                    </div>
                                    <div class="col-md-5">
                                        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

                                        @if (Model.Id != 0)
                                        {

                                        <input type="button" value="@GlobalRes.btnEdit" class="btn yellow Saveee" onclick="Save()" />
                                        }
                                        else
                                        {
                                            <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />

                                        }

                                    </div>
                                </div>


                                <br />
                                <div class="modal-header">
                                    <h4 class="modal-title"> اضافه بيانات التواصل   </h4>
                                </div>

                                <br />

                                <div class="row">
                                    <div class="col-md-2">
                                        <label>الاسم</label>
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" id="CommId" name="CommId" hidden />
                                        <input type="text" class="form-control" id="CommName" name="CommName">

                                        @*@Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                    <div class="col-md-2">
                                        <label>الوظيفه</label>
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="JobName" name="JobName">

                                        @*@Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-2">
                                        <label>الهاتف</label>
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="PhoneNumber" name="PhoneNumber">

                                        @*@Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                    <div class="col-md-2">
                                        <label>الاميل</label>
                                    </div>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="Email" name="Email">

                                        @*@Html.EditorFor(model => model.NameEn, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                </div>
                                <br />
                                <div class="row">

                                    <div class="col-md-6"></div>
                                    <div class="col-md-4">
                                       &nbsp; &nbsp; &nbsp; &nbsp;
                                        <input type="button" value="@GlobalRes.btnSave" class="btn yellow Saveee" onclick="Save()" />
                                    </div>

                                </div>
                                <br />
                                <br />
                                <br />

                                @if (Model.Id != 0)
                                {
                                    <div class="row">
                                        <div class="col-md-1"></div>
                                        <div class="col-md-10">
                                            <br />
                                            @Html.Action("CommunicationOfficer", new { Id = Model.Id })


                                        </div>
                                    </div>
                                }
                                <br />


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        @*</div>*@

        @*<div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>*@

        <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>



}



        <script>
            //$(document).ready(function () {
            //    $("input[type=text]").addClass("gui-input");
            //});

            function EditComm(Id, Name, JobName, PhoneNumber, Email) {
                $("#CommName").val(Name);
                $("#JobName").val(JobName);
                $("#PhoneNumber").val(PhoneNumber);
                $("#Email").val(Email);
                $("#CommId").val(Id);



            }
           
        </script>



        @section scripts {


            <script src="@Url.Content("~/Areas/BasicInput/Scripts/MangeCustomers.js")"></script>

            @*<script type="text/javascript">

                $(document).ready(function () {
                    ManageCustomers.init();

                })

            </script>*@
            <script src="~/Scripts/select2.min.js"></script>
            <script>
                $(document).ready(function () {
                    $('.select2').select2();
                    // $('.select5').select2();
                });
            </script>
<script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });

</script>
        }

Customers.Portal/Areas/BasicInput/Views/ManageCustomers/Delete.cshtml
@model CustomerVm


<div class="modal-dialog" style="width: 900px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
        </div>
        <div class="modal-body" style="width :900px;">

            <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
            <div class="row">
                <div class="col-md-3">
                    <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

Customers.Portal/Areas/BasicInput/Views/ManageCustomers/DeleteComm.cshtml
@model CommunicationOfficerVm


<div class="modal-dialog" style="width: 900px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"> @GlobalRes.btnDelete  </h4>
        </div>
        <div class="modal-body" style="width :900px;">

            <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ?????? </h4>
            <div class="row">
                <div class="col-md-3">
                    <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteCommRow(@Model.Id)" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

Customers.Portal/Areas/BasicInput/Views/ManageCustomers/Index1.cshtml
@{
//ViewBag.Title = GlobalRes.Cus;
}


<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/Home/index">@GlobalRes.MainPage</a>--  </h4>  <h4 class="page-title"> @GlobalRes.Customers </h4>
                    <br />

                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <a type="button" id="AddNew"  class="btn yellow " value="@GlobalRes.btnAdd" href="@Url.Action("Create")" >@GlobalRes.btnAdd </a>
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
                @*<div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>*@





                @section scripts {


                    <script src="@Url.Content("~/Areas/BasicInput/Scripts/MangeCustomers.js")"></script>

                    <script type="text/javascript">

                        $(document).ready(function () {
                            ManageCustomers.init();

                        })

                    </script>
                }

Customers.Portal/Areas/BasicInput/Views/ManageCustomers/Search.cshtml
@model IEnumerable<CustomerVm>

<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            @*<h4 class="m-t-0 header-title"><b>Default Example</b></h4>
            <p class="text-muted font-13 m-b-30">
                DataTables has most features enabled by default, so all you need to do to use it with your own tables is to call the construction function: <code>$().DataTable();</code>.
            </p>*@
            <table class="table table-hover table-bordered datatable" width="100%">
                <thead>
                    <tr>
                        <th>@BasicInputRes.Id</th>
                        <th>@BasicInputRes.NameAr</th>
                        <th>@BasicInputRes.NameEn</th>
                        <th>@Customers.Resources.Customers.CustomerRes.CustomerAddress</th>
                        <th>@Customers.Resources.Customers.CustomerRes.CustomerWebSite</th>
                        <th>@Customers.Resources.Customers.CustomerRes.Details</th>



                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
            {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.NameAr</td>
                            <td>@item.NameEn</td>
                            <td>@item.CustomerAddress</td>
                            <td>@item.CustomerWebSite</td>
                            <td>@item.Details</td>




                            <td>
                                <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                                    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-cog fa-lg"></i>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-xs pull-right">
                                        <li class="text-align-center">
                                            <a  class="btn btn-success   waves-effect waves-light m-b-0" id="btnUpdate" href="@Url.Action("Edit",new { Id=item.Id})">@GlobalRes.btnEdit</a>


                                            @*<button type="button" class="btn btn-success   waves-effect waves-light m-b-0" id="btnUpdate" onclick="Edit(@item.Id)">@GlobalRes.btnEdit</button>*@
                                        </li>
                                        <li class="divider"></li>
                                        <li class="text-align-center">
                                            <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete(@item.Id)"> @GlobalRes.btnDelete</button>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="text-align-center">
                                            <a href="javascript:void(0);" class="btn btn-warning waves-effect waves-light m-b-0" aria-hidden="true">@GlobalRes.btnCancel</a>
                                        </li>
                                    </ul>
                                </div>
                            </td>


                        </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>